CurateMyCommunity_Api/Areas/Admin/Models/ManageExhibits/CreateExhibitViewModel.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities;
using CurateMyCommunity_Api.Areas.Admin.Models.ManageImages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits
{
    public class CreateExhibitViewModel
    {
        public float latitude { get; set; }
        public float longitude { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_community { get; set; }
        public int id_image { get; set; }

    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageExhibits/EditExhibitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits
{
    public class EditExhibitViewModel
    {
        public int id_exhibits { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_community { get; set; }
        public int id_image { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageExhibits/ManageExhibitViewModel.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities;
using CurateMyCommunity_Api.Areas.Admin.Models.ManageImages;
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits
{
    public class ManageExhibitViewModel
    {
        public ManageExhibitViewModel()
        {

        }

        public ManageExhibitViewModel(Exhibit exhibitDTO)
        {
            id_exhibits = exhibitDTO.id_exhibits;
            latitude = exhibitDTO.latitude;
            longitude = exhibitDTO.longitude;
            name = exhibitDTO.name;
            description = exhibitDTO.description;
            id_community = exhibitDTO.tbl_id_communities;
            id_image = exhibitDTO.tbl_id_images;
        }

        public int id_exhibits { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_community { get; set; }
        public int id_image { get; set; }
        public bool is_selected { get; set; }

    }
}

CurateMyCommunity_Api/Models/ViewModels/Account/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class EditViewModel
    {
        [Required]
        public int id_user { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string username { get; set; }
        public string password { get; set; }
        public string passwordConfirm { get; set; }

    }
}

CurateMyCommunity_Api/Areas/Admin/Controllers/ManageExhibitsController.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits;
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurateMyCommunity_Api.Areas.Admin.Controllers
{
    [Authorize]
    public class ManageExhibitsController : Controller
    {
        // GET: Admin/ManageExhibits
        [HttpGet]
        public ActionResult Index()
        {//Setup a DbContext
            List<ManageExhibitViewModel> collectionOfExhibitsVM = new List<ManageExhibitViewModel>();
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //Get all Sessions
                var dbExhibits = context.Exhibits;

                //Move Sessions into a viewmodel object
                foreach (var exhibitDTO in dbExhibits)
                {
                    collectionOfExhibitsVM.Add(
                        new ManageExhibitViewModel(exhibitDTO)
                        );
                }
            }
            //send viewmodel collection to the View
            return View(collectionOfExhibitsVM);
        }

        // GET: Admin/ManageExhibits/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ManageExhibits/Create
        [HttpPost]
        public ActionResult Create(CreateExhibitViewModel newExhibit)
        {
            //Validate the New exhibit

            //Check that required fields are set
            if (!ModelState.IsValid)
            {
                return View(newExhibit);
            }
            //Create an instance of our DbContext
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //Make sure the exhibit name is unique
                if (context.Exhibits.Any(row => row.name.Equals(newExhibit.name)))
                {
                    ModelState.AddModelError("", "Exhibit name already exists. Try Again.");
                    newExhibit.name = "";
                    return View(newExhibit);
                }
                //Create our exhibit DTO
                Exhibit newExhibitDTO = new CurateMyCommunity_Api.Models.Data.Exhibit()
                {
                    latitude = newExhibit.latitude,
                    longitude = newExhibit.longitude,
                    name = newExhibit.name,
                    description = newExhibit.description,
                    tbl_id_communities = newExhibit.id_community,
                    tbl_id_images = newExhibit.id_image
            };
                //Add to DbContext
                newExhibitDTO = context.Exhibits.Add(newExhibitDTO);
                //Save Changes
                context.SaveChanges();
            }
            //Redirect to Exhibit list
            return RedirectToAction("Index");
        }

        // GET: Admin/ManageExhibits/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Get the session by Id

            EditExhibitViewModel editExhibitVM;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get user from database
                Exhibit exhibitDTO = context.Exhibits.Find(id);

                if (exhibitDTO == null)
                {
                    return Content("Invalid Id");
                }
                // create a EditViewModel
                editExhibitVM = new EditExhibitViewModel()
                {
                    id_exhibits = exhibitDTO.id_exhibits,
                    latitude = exhibitDTO.latitude,
                    longitude = exhibitDTO.longitude,
                    name = exhibitDTO.name,
                    description = exhibitDTO.description,
                    id_community = exhibitDTO.tbl_id_communities,
                    id_image = exhibitDTO.tbl_id_images
                };
            }
            // Send the viewmodel to the view
            return View(editExhibitVM);
        }

        // POST: Admin/ManageExhibits/Edit/5
        [HttpPost]
        public ActionResult Edit(EditExhibitViewModel editVM)
        {
            //Validate Model
            if (!ModelState.IsValid)
            {
                return View(editVM);
            }
            //get session from the database
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                Exhibit sessionDTO = context.Exhibits.Find(editVM.id_exhibits);

                if (sessionDTO == null) { return Content("Invalid Exhibit"); }

                //set update values
                sessionDTO.name = editVM.name;
                sessionDTO.latitude = editVM.latitude;
                sessionDTO.longitude = editVM.longitude;
                sessionDTO.description = editVM.description;
                sessionDTO.tbl_id_communities = editVM.id_community;
                sessionDTO.tbl_id_images = editVM.id_image;

                //save changes
                context.SaveChanges();

            }


            return RedirectToAction("Index");
        }

        // GET: Admin/ManageExhibits/Delete
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/ManageExhibits/Delete
        [HttpPost]
        public ActionResult Delete(List<ManageExhibitViewModel> collectionOfExhibitsVM)
        {
            //filter collection of users on is selected
            var vmExhibitsToDelete = collectionOfExhibitsVM.Where(x => x.is_selected == true);

            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //loop through view models items
                foreach (var vmItem in vmExhibitsToDelete)
                {
                    var dtoToDelete = context.Exhibits.FirstOrDefault(row => row.id_exhibits == vmItem.id_exhibits);
                    context.Exhibits.Remove(dtoToDelete);

                }
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageExhibits/Create.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits.CreateExhibitViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exhibit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_community, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_community, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_community, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageExhibits/Edit.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits.EditExhibitViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exhibit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_exhibits)

        <div class="form-group">
            @Html.LabelFor(model => model.latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_community, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_community, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_community, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageExhibits/Index.cshtml
@model List<CurateMyCommunity_Api.Areas.Admin.Models.ManageExhibits.ManageExhibitViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Exhibits</h2>

<p>
    @Html.ActionLink("Create New", "Create", "ManageExhibits")
</p>
@using (Html.BeginForm("Delete", "ManageExhibits"))
{
<table class="table">
    <tr>
        <th>
            &nbsp;
        </th>
        <th>
            Id
        </th>
        <th>
            Latitude
        </th>
        <th>
            Longitude
        </th>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Community Id
        </th>
        <th>
            Image Id
        </th>
        <th></th>
    </tr>

@for (int i = 0; i < Model.Count; i++)
{
    var item = Model[i];
    <tr>
        <td>
            @Html.HiddenFor(x => Model[i].id_exhibits)
            @Html.CheckBoxFor(x => Model[i].is_selected)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_exhibits)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.latitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_community)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_image)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id_exhibits })
        </td>
    </tr>
}

</table>
<button type="submit" class="btn btn-danger">Delete Selected</button>
}