CurateMyCommunity_Api/Areas/Admin/Models/ManageImages/CreateImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageImages
{
    public class CreateImageViewModel
    {
        public string image_url { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageImages/EditImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageImages
{
    public class EditImageViewModel
    {
        public int id_images { get; set; }
        public string  image_url { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageImages/ManageImageViewModel.cs
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageImages
{
    public class ManageImageViewModel
    {
        public ManageImageViewModel()
        {
        }

        public ManageImageViewModel(Image imageDTO)
        {
            id_images = imageDTO.id_images;
            image_url = imageDTO.image_url;

        }

        public int id_images { get; set; }

        public string image_url { get; set; }
        public bool is_selected { get; set; }
    }
}

CurateMyCommunity_Api/Models/ViewModels/Account/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class EditViewModel
    {
        [Required]
        public int id_user { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string username { get; set; }
        public string password { get; set; }
        public string passwordConfirm { get; set; }

    }
}

CurateMyCommunity_Api/Areas/Admin/Controllers/ManageImagesController.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageImages;
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurateMyCommunity_Api.Areas.Admin.Controllers
{
    [Authorize]
    public class ManageImagesController : Controller
    {
        // GET: Admin/ManageImages
        public ActionResult Index()
        {
            List<ManageImageViewModel> collectionOfImagesVM = new List<ManageImageViewModel>();
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //Get all Sessions
                var dbImage = context.Images;

                //Move Sessions into a viewmodel object
                foreach (var imageDTO in dbImage)
                {
                    collectionOfImagesVM.Add(
                        new ManageImageViewModel(imageDTO)
                        );
                }
            }
            //send viewmodel collection to the View
            return View(collectionOfImagesVM);
        }

        [HttpGet]
        // GET: Admin/ManageImages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ManageImages/Create
        [HttpPost]
        public ActionResult Create(CreateImageViewModel newImage)
        {
            //Validate the New User

            //Check that required fields are set
            if (!ModelState.IsValid)
            {
                return View(newImage);
            }
            //Create an instance of our DbContext
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //Make sure the username is unique
                if (context.Images.Any(row => row.image_url.Equals(newImage.image_url)))
                {
                    ModelState.AddModelError("", "Image already exists. Try Again.");
                    newImage.image_url = "";
                    return View(newImage);
                }
                //Create our session DTO
                Image newImageDTO = new CurateMyCommunity_Api.Models.Data.Image()
                {
                    image_url = newImage.image_url

                };
                //Add to DbContext
                newImageDTO = context.Images.Add(newImageDTO);
                //Save Changes
                context.SaveChanges();
            }
            //Redirect to login page
            return RedirectToAction("Index");
        }

        // GET: Admin/ManageImages/Edit/5
        public ActionResult Edit(int id)
        {
            EditImageViewModel editImageVM;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get user from database
                Image imageDTO = context.Images.Find(id);

                if (imageDTO == null)
                {
                    return Content("Invalid Id");
                }
                // create a EditViewModel
                editImageVM = new EditImageViewModel()
                {
                    id_images = imageDTO.id_images,
                    image_url = imageDTO.image_url
                };
            }
            // Send the viewmodel to the view
            return View(editImageVM);
        }

        // POST: Admin/ManageImages/Edit/5
        [HttpPost]
        public ActionResult Edit(EditImageViewModel editVM)
        {
            //Validate Model
            if (!ModelState.IsValid)
            {
                return View(editVM);
            }
            //get session from the database
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                Image imageDTO = context.Images.Find(editVM.id_images);

                if (imageDTO == null) { return Content("Invalid Image"); }

                //set update values
                imageDTO.image_url = editVM.image_url;

                //save changes
                context.SaveChanges();

            }


            return RedirectToAction("Index");
        }
        // POST: Admin/ManageImages/Delete/5
        [HttpPost]
        public ActionResult Delete(List<ManageImageViewModel> collectionOfImagesVM)
        {
            //filter collection of users on is selected
            var vmImagesToDelete = collectionOfImagesVM.Where(x => x.is_selected == true);

            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //loop through view models items
                foreach (var vmItem in vmImagesToDelete)
                {
                    var dtoToDelete = context.Images.FirstOrDefault(row => row.id_images == vmItem.id_images);
                    context.Images.Remove(dtoToDelete);

                }
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageImages/Create.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageImages.CreateImageViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.image_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageImages/Edit.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageImages.EditImageViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_images)

        <div class="form-group">
            @Html.LabelFor(model => model.image_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageImages/Index.cshtml
@model List<CurateMyCommunity_Api.Areas.Admin.Models.ManageImages.ManageImageViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "ManageImages")
</p>

@using (Html.BeginForm("Delete", "ManageImages"))
{
<table class="table">
    <tr>
        <th>
            &nbsp;
        </th>
        <th>
            Id
        </th>
        <th>
            Image Url
        </th>
        <th></th>
    </tr>

@for (int i = 0; i < Model.Count; i++)
{
    var item = Model[i];
    <tr>
        <td>
            @Html.HiddenFor(x => Model[i].id_images)
            @Html.CheckBoxFor(x => Model[i].is_selected)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_images)
        </td>
        <td>
            <a href="@Html.DisplayFor(modelItem => item.image_url)">@Html.DisplayFor(modelItem => item.image_url)</a>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id_images })
        </td>
    </tr>
}

</table>
<button type="submit" class="btn btn-danger">Delete Selected</button>
}