CurateMyCommunity_Api/Models/ViewModels/Account/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class EditViewModel
    {
        [Required]
        public int id_user { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string username { get; set; }
        public string password { get; set; }
        public string passwordConfirm { get; set; }

    }
}

CurateMyCommunity_Api/Models/ViewModels/Account/UserNavPartialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class UserNavPartialViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

CurateMyCommunity_Api/Models/ViewModels/Account/UserProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class UserProfileViewModel
    {
        public int id_user { get; set; }
        public string  firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public DateTime dateCreated { get; set; }
    }
}

CurateMyCommunity_Api/Controllers/AccountLoginController.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageUsers;
using CurateMyCommunity_Api.Models.Data;
using CurateMyCommunity_Api.Models.ViewModels.Account;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CurateMyCommunity_Api.Controllers
{
    public class AccountLoginController : Controller
    {
        // GET: AccountLogin
        public ActionResult Index()
        {
            return this.RedirectToAction("Login");
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginUserViewModel loginUser)
        {
            if (loginUser == null)
            {
                ModelState.AddModelError("", "Login is Required");
                return View();
            }

            if (string.IsNullOrWhiteSpace(loginUser.username))
            {
                ModelState.AddModelError("", "Username is Required");
                return View();
            }

            if (string.IsNullOrWhiteSpace(loginUser.password))
            {
                ModelState.AddModelError("", "Password is Required");
                return View();
            }

            //Open database connection
            bool isValid = false;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //search for logging in user
                Models.Data.User UserDTO = context.Users.FirstOrDefault(x => x.username == loginUser.username);
                // get current users hashed password
                string correcthash = UserDTO.password;
                //hash password
                bool passwordhash = PasswordStorage.VerifyPassword(loginUser.password, correcthash);
                //query for user based on username and password hash
                if (context.Users.Any(row => row.username.Equals(loginUser.username)) && passwordhash)
                {
                    isValid = true;
                }
            }

            //if invalid, send error
            if (!isValid)
            {
                ModelState.AddModelError("", "Invalid Username or Password");
                return View();
            }
            else
            {
                //valid, redirect to user profile

                System.Web.Security.FormsAuthentication.SetAuthCookie(loginUser.username, loginUser.rememberMe);
                FormsAuthentication.GetRedirectUrl(loginUser.username, loginUser.rememberMe);
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            //HttpContext.User = new GenericPrincipal(new GenericIdentity(string.Empty), null);

            return RedirectToAction("Login");
        }

        public ActionResult UserNavPartial()
        {
            // capture logged in user
            string username;
            username = this.User.Identity.Name;

            // get user information form database
            UserNavPartialViewModel userNavVM;

            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // search for user
                Models.Data.User UserDTO = context.Users.FirstOrDefault(x => x.username == username);

                if (UserDTO == null) { return Content(""); }
                // build our UserNavPartialViewModel
                userNavVM = new UserNavPartialViewModel()
                {
                    FirstName = UserDTO.firstname,
                    LastName = UserDTO.lastname,
                    Id = UserDTO.id_users
                };
            }

            // Build our usernavPartial viewmodel

            // send the view model to the patriel view

            return PartialView(userNavVM);
        }

        public ActionResult UserProfile(int? id = null)
        {
            // Capture Logged in User
            string username = User.Identity.Name;

            // Retrieve the user from database
            UserProfileViewModel profileVM;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get User from the database
                User userDTO;
                if (id.HasValue)
                {
                    userDTO = context.Users.Find(id.Value);
                }
                else
                {
                    userDTO = context.Users.FirstOrDefault(row => row.username == username);
                }

                if (userDTO == null)
                {
                    return Content("Invalid Username");
                }
                // populate our UserProfileViewModel
                profileVM = new UserProfileViewModel()
                {
                    dateCreated = userDTO.date_created,
                    email = userDTO.email,
                    firstname = userDTO.firstname,
                    id_user = userDTO.id_users,
                    lastname = userDTO.lastname,
                    username = userDTO.username
                };
            }

            // Return the view with the ViewModel
            return View(profileVM);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Get the user by Id

            EditViewModel editVM;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get user from database
                User userDTO = context.Users.Find(id);

                if (userDTO == null)
                {
                    return Content("Invalid Id");
                }
                // create a EditViewModel
                editVM = new EditViewModel()
                {
                    id_user = userDTO.id_users,
                    email = userDTO.email,
                    firstname = userDTO.firstname,
                    lastname = userDTO.lastname,
                    username = userDTO.username
                };
            }
            // Send the viewmodel to the view
            return View(editVM);
        }

        [HttpPost]
        public ActionResult Edit(EditViewModel editVM)
        {
            //Variables
            bool needsPasswordReset = false;
            bool usernameHasChanged = false;

            // Validate Model
            if (!ModelState.IsValid)
            {
                return View(editVM);
            }

            //Check for password change
            if (!string.IsNullOrWhiteSpace(editVM.password))
            {
                //Compare password with password confirm
                if (editVM.password != editVM.passwordConfirm)
                {
                    ModelState.AddModelError("", "Password and PasswordConfirm must match");
                    return View(editVM);
                }
                else
                {
                    needsPasswordReset = true;
                }
            }
            // get our user form the database
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get our DTO
                User userDTO = context.Users.Find(editVM.id_user);
                if (userDTO == null) { return Content("Invalid User Id"); }

                // CHeck for username change
                if (userDTO.username != editVM.username)
                {

                    userDTO.username = editVM.username;
                    usernameHasChanged = true;
                }

                // set/update values from the viewmodel
                userDTO.firstname = editVM.firstname;
                userDTO.email = editVM.email;
                userDTO.lastname = editVM.lastname;

                if (needsPasswordReset)
                {
                    userDTO.password = PasswordStorage.CreateHash(editVM.password);
                }
                // save changes
                context.SaveChanges();
            }
            if (usernameHasChanged || needsPasswordReset)
            {
                TempData["LogoutMessage"] = "After a username or password change. Please log in with the new credentials.";
                return RedirectToAction("Logout");
            }
            return RedirectToAction("UserProfile");
        }
    }
}

CurateMyCommunity_Api/Views/AccountLogin/Edit.cshtml
@model CurateMyCommunity_Api.Models.ViewModels.Account.EditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Account Details</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_user)

        <div class="form-group">
            @Html.LabelFor(model => model.firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.passwordConfirm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.passwordConfirm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passwordConfirm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Views/AccountLogin/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@Html.ValidationSummary()
@if (TempData["LogoutMessage"] != null)
{
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-warning-sign"></span>
        @TempData["LogoutMessage"]
    </div>
}
<form method="post" action="/AccountLogin/Login">
    <label>Username: </label><input type="text" name="username" /><br />
    <label>Password: </label><input type="password" name="password" /><br />
    <button type="submit" name="login">Login</button> <br />
    <input type="checkbox" name="rememberLogin" value="true" /> Remember Me <br />
</form>

CurateMyCommunity_Api/Views/AccountLogin/UserNavPartial.cshtml
@model CurateMyCommunity_Api.Models.ViewModels.Account.UserNavPartialViewModel
<a href="@Url.Action("UserProfile", "AccountLogin")">(@Model.FirstName @Model.LastName)</a>

CurateMyCommunity_Api/Views/AccountLogin/UserProfile.cshtml
@model CurateMyCommunity_Api.Models.ViewModels.Account.UserProfileViewModel

@{
    ViewBag.Title = "UserProfile";
}

<h2>UserProfile</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_user })
</p>