CurateMyCommunity_Api/Areas/Admin/Models/ManageCommunities/CreateCommunityViewModel.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageHosts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities
{
    public class CreateCommunityViewModel
    {
        public string community { get; set; }

        public string city { get; set; }

        public string state { get; set; }

        public int id_host { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageCommunities/EditCommunityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities
{
    public class EditCommunityViewModel
    {
        [Required]
        public int id_communities { get; set; }
        public string community { get; set; }

        public string city { get; set; }

        public string state { get; set; }

        public int id_host { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageCommunities/ManageCommunityViewModel.cs
using CurateMyCommunity_Api.Areas.Admin.Models.ManageHosts;
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities
{
    public class ManageCommunityViewModel
    {
        public ManageCommunityViewModel()
        {

        }

        public ManageCommunityViewModel(Community communityDTO)
        {
            id_communities = communityDTO.id_communities;
            community = communityDTO.community;
            city = communityDTO.city;
            state = communityDTO.state;
            id_host = communityDTO.tbl_id_hosts;
        }

        public int id_communities { get; set; }
        public string community { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int id_host { get; set; }
        public bool is_selected { get; set; }
    }
}

CurateMyCommunity_Api/Areas/Admin/Models/ManageCommunties/ManageCommunityViewModel.cs
using CurateMyCommunity_Api.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunties
{
    public class ManageCommunityViewModel
    {
        public ManageCommunityViewModel()
        {

        }

        public ManageCommunityViewModel(Community communityDTO)
        {
            id_communities = communityDTO.id_communties;
            community = communityDTO.community;
            city = communityDTO.city;
            state = communityDTO.state;
            host = communityDTO.host;
            twitter_handle = communityDTO.twitter_handle;
        }

        public int id_communities { get; set; }
        public string community { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string host { get; set; }
        public string twitter_handle { get; set; }
        public bool is_selected { get; set; }
    }
}

CurateMyCommunity_Api/Models/ViewModels/Account/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CurateMyCommunity_Api.Models.ViewModels.Account
{
    public class EditViewModel
    {
        [Required]
        public int id_user { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string lastname { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string username { get; set; }
        public string password { get; set; }
        public string passwordConfirm { get; set; }

    }
}

CurateMyCommunity_Api/Areas/Admin/Controllers/ManageCommunitiesController.cs
using CurateMyCommunity_Api.Models.Data;
using CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurateMyCommunity_Api.Areas.Admin.Controllers
{
    [Authorize]
    public class ManageCommunitiesController : Controller
    {
        // GET: Admin/ManageCommunity
        [HttpGet]
        public ActionResult Index()
        {
            List<ManageCommunityViewModel> collectionOfSessionsVM = new List<ManageCommunityViewModel>();
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //Get all Sessions
                var dbCommunity = context.Communities;

                //Move Sessions into a viewmodel object
                foreach (var communityDTO in dbCommunity)
                {
                    collectionOfSessionsVM.Add(
                        new ManageCommunityViewModel(communityDTO)
                        );
                }
            }
            //send viewmodel collection to the View
            return View(collectionOfSessionsVM);
        }

        // GET: Admin/ManageCommunity/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ManageCommunity/Create
        [HttpPost]
        public ActionResult Create(CreateCommunityViewModel newCommunity)
        {
            //Validate the New User

            //Check that required fields are set
            if (!ModelState.IsValid)
            {
                return View(newCommunity);
            }
            //Create an instance of our DbContext
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //get host name

                //Make sure the community is unique
                if (context.Communities.Any(row => row.community.Equals(newCommunity.community)))
                {
                    ModelState.AddModelError("", "Community already exists. Try Again.");
                    newCommunity.community = "";
                    return View(newCommunity);
                }
                //Create our community DTO
                Community newCommunityDTO = new CurateMyCommunity_Api.Models.Data.Community()
                {
                    community = newCommunity.community,
                    city = newCommunity.city,
                    state = newCommunity.state,
                    tbl_id_hosts = newCommunity.id_host
            };
                //Add to DbContext
                newCommunityDTO = context.Communities.Add(newCommunityDTO);
                //Save Changes
                context.SaveChanges();
            }
            //Redirect to login page
            return RedirectToAction("Index");
        }

        // GET: Admin/ManageCommunity/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Get the community by Id

            EditCommunityViewModel editCommunityVM;
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                // Get user from database
                Community communityDTO = context.Communities.Find(id);

                if (communityDTO == null)
                {
                    return Content("Invalid Id");
                }
                // create a EditViewModel
                editCommunityVM = new EditCommunityViewModel()
                {
                    id_communities = communityDTO.id_communities,
                    community = communityDTO.community,
                    city = communityDTO.city,
                    state = communityDTO.state,
                    id_host = communityDTO.tbl_id_hosts
            };
            }
            // Send the viewmodel to the view
            return View(editCommunityVM);
        }

        // POST: Admin/ManageCommunity/Edit/5
        [HttpPost]
        public ActionResult Edit(EditCommunityViewModel editVM)
        {
            //Validate Model
            if (!ModelState.IsValid)
            {
                return View(editVM);
            }
            //get community from the database
            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                Community communityDTO = context.Communities.Find(editVM.id_communities);

                if (communityDTO == null) { return Content("Invalid Community"); }

                //set update values
                communityDTO.community = editVM.community;
                communityDTO.city = editVM.city;
                communityDTO.state = editVM.state;
                communityDTO.tbl_id_hosts = editVM.id_host;

                //save changes
                context.SaveChanges();

            }


            return RedirectToAction("Index");
        }

        // GET: Admin/ManageCommunity/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/ManageCommunity/Delete/5
        [HttpPost]
        public ActionResult Delete(List<ManageCommunityViewModel> collectionOfCommunityVM)
        {
            //filter collection of communities on is selected
            var vmSessionsToDelete = collectionOfCommunityVM.Where(x => x.is_selected == true);

            using (CMC_DB_Connection context = new CMC_DB_Connection())
            {
                //loop through view models items
                foreach (var vmItem in vmSessionsToDelete)
                {
                    var dtoToDelete = context.Communities.FirstOrDefault(row => row.id_communities == vmItem.id_communities);
                    context.Communities.Remove(dtoToDelete);

                }
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageCommunities/Create.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities.CreateCommunityViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Community</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.community, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.community, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.community, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_host, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageCommunities/Edit.cshtml
@model CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities.EditCommunityViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Community</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_communities)

        <div class="form-group">
            @Html.LabelFor(model => model.community, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.community, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.community, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_host, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CurateMyCommunity_Api/Areas/Admin/Views/ManageCommunities/Index.cshtml
@model List<CurateMyCommunity_Api.Areas.Admin.Models.ManageCommunities.ManageCommunityViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Communities</h2>

<p>
    @Html.ActionLink("Create New", "Create", "ManageCommunities")
</p>

@using (Html.BeginForm("Delete", "ManageCommunities"))
{
<table class="table">
    <tr>
        <th>
            &nbsp;
        </th>
        <th>
            Id
        </th>
        <th>
            Community
        </th>
        <th>
            City
        </th>
        <th>
            State
        </th>
        <th>
            Host
        </th>
        <th></th>
    </tr>

@for (int i = 0; i < Model.Count; i++)
{
    var item = Model[i];
    <tr>
        <td>
            @Html.HiddenFor(x => Model[i].id_communities)
            @Html.CheckBoxFor(x => Model[i].is_selected)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_communities)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.community)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.state)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_host)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id_communities })
        </td>
    </tr>
}

</table>
<button type="submit" class="btn btn-danger">Delete Selected</button>
}